<html>
<head>    <meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
	<title></title>

	<link rel='stylesheet' href='tur.css' type="text/css">
</head>
<body >

<table  width=100%><tr><td width=120 class=devel>Web разработчик<br>  ________<br>
 <a href=mailto:cha@hotmail.com>cha@hotmail.com</a> <br>Все права защищены<br>  2014 </td>
 <td align=center ><img src='img/FNT05BAN.GIF'></td></tr>
 <tr><td >